<?php die(); ?><!DOCTYPE html>
	<!--[if IE 8]>
		<html xmlns="http://www.w3.org/1999/xhtml" class="ie8" lang="ja"
	itemscope 
	itemtype="http://schema.org/WebSite" 
	prefix="og: http://ogp.me/ns#" >
	<![endif]-->
	<!--[if !(IE 8) ]><!-->
		<html xmlns="http://www.w3.org/1999/xhtml" lang="ja"
	itemscope 
	itemtype="http://schema.org/WebSite" 
	prefix="og: http://ogp.me/ns#" >
	<!--<![endif]-->
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>SRM_COM_SITE &lsaquo; ログイン</title>
	<link rel='dns-prefetch' href='//s.w.org' />
<link rel='stylesheet' href='http://localhost:8888/wordpress/wp-admin/load-styles.php?c=1&amp;dir=ltr&amp;load%5B%5D=dashicons,buttons,forms,l10n,login&amp;ver=4.6.1' type='text/css' media='all' />
<link rel='stylesheet' id='yarppWidgetCss-css'  href='http://localhost:8888/wordpress/wp-content/plugins/yet-another-related-posts-plugin/style/widget.css?ver=4.6.1' type='text/css' media='all' />
<meta name='robots' content='noindex,follow' />
	</head>
	<body class="login login-action-login wp-core-ui  locale-ja">
		<div id="login">
		<h1><a href="https://ja.wordpress.org/" title="Powered by WordPress" tabindex="-1">SRM_COM_SITE</a></h1>
	
<form name="loginform" id="loginform" action="http://localhost:8888/wordpress/login_27670" method="post">
	<p>
		<label for="user_login">ユーザー名またはメールアドレス<br />
		<input type="text" name="log" id="user_login" class="input" value="admin" size="20" /></label>
	</p>
	<p>
		<label for="user_pass">パスワード<br />
		<input type="password" name="pwd" id="user_pass" class="input" value="" size="20" /></label>
	</p>
	<p><img src="http://localhost:8888/wordpress/wp-content/plugins/siteguard/really-simple-captcha/tmp/1666352941.png" alt="CAPTCHA"></p><p><label for="siteguard_captcha">上に表示された文字を入力してください。</label><br /><input type="text" name="siteguard_captcha" id="siteguard_captcha" class="input" value="" size="10" aria-required="true" /><input type="hidden" name="siteguard_captcha_prefix" id="siteguard_captcha_prefix" value="1666352941" /></p>	<p class="forgetmenot"><label for="rememberme"><input name="rememberme" type="checkbox" id="rememberme" value="forever"  /> ログイン状態を保存する</label></p>
	<p class="submit">
		<input type="submit" name="wp-submit" id="wp-submit" class="button button-primary button-large" value="ログイン" />
		<input type="hidden" name="redirect_to" value="http://localhost:8888/wordpress/wp-admin/" />
		<input type="hidden" name="testcookie" value="1" />
	</p>
</form>

<p id="nav">
	<a href="http://localhost:8888/wordpress/login_27670?action=lostpassword">パスワードをお忘れですか ?</a>
</p>

<script type="text/javascript">
function wp_attempt_focus(){
setTimeout( function(){ try{
d = document.getElementById('user_pass');
d.value = '';
d.focus();
d.select();
} catch(e){}
}, 200);
}

wp_attempt_focus();
if(typeof wpOnload=='function')wpOnload();
</script>

	<p id="backtoblog"><a href="http://localhost:8888/wordpress/">&larr; SRM_COM_SITE に戻る</a></p>
	
	</div>

	
		<div class="clear"></div>
	</body>
	</html>
	
<!-- Dynamic page generated in 3.941 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-10-04 16:43:31 -->
